#!/bin/bash
set -e

echo "当前工作目录: $(pwd)"

mkdir /mnt/runner-will-upload
rm /mnt/DATALOSS_WARNING_README.txt
apt-get update
apt-get install -y pbzip2 nano qemu-kvm

(
    cd /mnt/current-running/arts || exit 1
    echo "解压工作目录: $(pwd)" || exit 1
    tar --use-compress-program=pbzip2 -xf fedora.tar.bz2 -C /mnt/current-running || exit 1
)

rm -rf /mnt/current-running/arts || exit 1
