name: download from before runner (vm-fedora-encrypt)
on:
  workflow_dispatch:
    inputs:
      LINK:
        description: 'the before runner id'
        required: true
        default: '13303124913'
env:
  GH_TOKEN: ${{ secrets.GH_TOKEN }}
jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - run: echo ${{ secrets.GH_TOKEN }} > ghtoken.txt
      - run: sudo gh auth login --with-token < ghtoken.txt
      - run: rm ghtoken.txt
      
      - run: chmod +x ./setup-ssh
      - run: chmod +x ./auto-tar
      - run: chmod +x ./auto-patch-environment-and-untar
      - run: sudo mkdir /mnt/current-running
      - run: sudo mv ./kvm-fedora /mnt/current-running/kvm
      - run: sudo chmod +x /mnt/current-running/kvm

      - run: sudo gh run download ${{ github.event.inputs.LINK }} --dir /mnt/current-running --repo scevwvrvebv/Action-ssh

      - name: Handle Fedora tarball
        shell: bash
        run: |
            set -euo pipefail
            ARTIFACTS_DIR="/mnt/current-running/arts"
    
            shopt -s nullglob
            matched_files=("$ARTIFACTS_DIR"/fedora-*.tar.bz2)
            shopt -u nullglob
            file_count=${#matched_files[@]}

                if [ $file_count -eq 1 ]; then
                  echo "Found single Fedora tarball: ${matched_files[0]}"
                  sudo mv -v "${matched_files[0]}" "$ARTIFACTS_DIR/fedora.tar.bz2"
                  echo "Renamed ${matched_files[0]} to fedora.tar.bz2"
                elif [ $file_count -gt 1 ]; then
                  echo "::error::Multiple Fedora tarballs detected:"
                  printf '  %s\n' "${matched_files[@]}"
                  exit 1
                else
                  echo "No Fedora tarballs found"
                fi

      - run: sudo sh ./auto-patch-environment-and-untar

      - run: $GITHUB_WORKSPACE/setup-ssh
        shell: bash

      - run: sudo apt-get install guestfs-tools -y --no-install-recommends

      - run: sudo sh ./auto-tar

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: arts
          path: /mnt/runner-will-upload/*
